# Generated by Django 2.0.3 on 2021-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_code_usecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='discount',
            field=models.IntegerField(default=1, verbose_name='Min price'),
            preserve_default=False,
        ),
    ]
