# Generated by Django 2.0.3 on 2021-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_code_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='discount',
            field=models.IntegerField(verbose_name='Discount'),
        ),
    ]
