# Generated by Django 2.0.3 on 2021-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20210215_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='type_discount',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=30, verbose_name='Type discount'),
        ),
    ]
