# Generated by Django 2.0.3 on 2021-05-22 08:59

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210522_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '1300x702', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
    ]
