# Generated by Django 2.0.3 on 2021-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210120_2120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Color', 'verbose_name_plural': 'Colors'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productcolor',
            options={'verbose_name': 'Product color', 'verbose_name_plural': 'Product colors'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AddField(
            model_name='productcolor',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is it available?'),
        ),
        migrations.AlterUniqueTogether(
            name='productcolor',
            unique_together=set(),
        ),
    ]
