# Generated by Django 2.0.3 on 2021-02-02 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210120_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is it available?')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product color',
                'verbose_name_plural': 'Product colors',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=30, verbose_name='Name size')),
                ('size', models.CharField(max_length=30, verbose_name='Size')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=30, verbose_name='Name size chart')),
            ],
            options={
                'verbose_name': 'Size Chart',
                'verbose_name_plural': 'Size Charts',
            },
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcolor',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
        migrations.AddField(
            model_name='size',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.SizeChart', verbose_name='Chart'),
        ),
        migrations.AddField(
            model_name='productsizecolor',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size', verbose_name='Size'),
        ),
    ]
