# Generated by Django 2.0.3 on 2021-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210202_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizechart',
            name='table',
            field=models.TextField(default=1, verbose_name='Table'),
            preserve_default=False,
        ),
    ]
