# Generated by Django 2.0.3 on 2021-02-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_sizechart_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='size',
        ),
    ]
