# Generated by Django 2.0.3 on 2021-02-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210202_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
