# Generated by Django 2.0.3 on 2021-02-03 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
        ('product', '0010_auto_20210202_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('moderated', 'Moderated')], default='moderated', max_length=30, verbose_name='Status')),
                ('star', models.CharField(choices=[('star1', 'star1'), ('star2', 'star2'), ('star3', 'star3'), ('star4', 'star4'), ('star5', 'star5')], max_length=30, verbose_name='Star')),
                ('text', models.TextField(verbose_name='Text')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Color', verbose_name='Color')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Guest', verbose_name='Guest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size', verbose_name='Size')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='FeedbackImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(upload_to='feedback/image', verbose_name='Image')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Feedback', verbose_name='Feedback')),
            ],
            options={
                'verbose_name': 'Feedback image',
                'verbose_name_plural': 'Feedback images',
            },
        ),
    ]
