# Generated by Django 2.0.3 on 2021-02-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_feedback_feedbackimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('product', 'color')},
        ),
    ]
