# Generated by Django 2.0.3 on 2021-02-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20210207_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='works_best_with',
            field=models.ManyToManyField(blank=True, null=True, to='product.Product', verbose_name='Works best with'),
        ),
    ]
