# Generated by Django 2.0.3 on 2021-02-10 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_code_usecode'),
        ('product', '0019_product_works_best_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Code', verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('sent', 'Sent'), ('processing', 'Processing'), ('new', 'New'), ('rejected', 'rejected')], default='new', max_length=30, verbose_name='Status'),
        ),
    ]
