# Generated by Django 2.0.3 on 2021-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_auto_20210210_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Discount'),
        ),
    ]
