# Generated by Django 2.0.3 on 2021-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20210214_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='pay',
            field=models.CharField(choices=[('card', 'Card'), ('delivery', 'Delivery')], default='delivery', max_length=30, verbose_name='Pay'),
        ),
    ]
