# Generated by Django 2.0.3 on 2021-02-18 11:42

from django.db import migrations, models
import django.db.models.deletion
from product.models import ProductSizeColor, ProductSizeColorSize


def size_up(apps, schema_editor):
    for product_size_color in ProductSizeColor.objects.all():
        for size in product_size_color.sizes.all():
            ProductSizeColorSize.objects.create(size=size, product_size_color=product_size_color)


def size_down(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0023_auto_20210215_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeColorSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('count', models.IntegerField(default=0, verbose_name='Count')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is it available?')),
                ('product_size_color',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductSizeColor',
                                   verbose_name='Product color')),
            ],
            options={
                'verbose_name': 'Product color size',
                'verbose_name_plural': 'Product color sizes',
            },
        ),
        migrations.AddField(
            model_name='size',
            name='size',
            field=models.CharField(default='xs', max_length=30, verbose_name='Type size'),
        ),
        migrations.AddField(
            model_name='productsizecolorsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size',
                                    verbose_name='Size'),
        ),
        migrations.RunPython(size_up, size_down),
    ]
