# Generated by Django 2.0.3 on 2021-02-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20210218_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Is completed'),
        ),
    ]
