# Generated by Django 2.0.3 on 2021-02-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_basket_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='New'),
        ),
        migrations.AlterField(
            model_name='product',
            name='accessories_type',
            field=models.CharField(blank=True, choices=[('shoe_accessories', 'Shoe accessories'), ('bags', 'Bags'), ('ladies_accessories', 'Ladies accessories')], max_length=30, null=True, verbose_name='Accessories type'),
        ),
    ]
