# Generated by Django 2.0.3 on 2021-02-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_auto_20210226_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
