# Generated by Django 2.0.3 on 2021-03-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='Total price'),
        ),
    ]
