# Generated by Django 2.0.3 on 2021-05-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_basket_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['created_at'], 'verbose_name': 'Product image', 'verbose_name_plural': 'Product images'},
        ),
        migrations.AddField(
            model_name='basket',
            name='code_delivery',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code - delivery'),
        ),
    ]
