# Generated by Django 2.0.3 on 2021-12-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_auto_20210518_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ladies_type',
            field=models.CharField(blank=True, choices=[('leotards', 'Leotards'), ('body', 'Body(old)'), ('blouses', 'Blouses'), ('skirts', 'Skirts'), ('dresses', 'Dresses'), ('pants', 'Pants'), ('trousers', 'Trousers(old)'), ('jumpsuits', 'Jumpsuits'), ('tops', 'Tops'), ('shorts', 'Shorts')], max_length=30, null=True, verbose_name='Ladies type'),
        ),
    ]
