# Generated by Django 2.0.3 on 2022-08-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20211222_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=0, verbose_name='Is_new'),
            preserve_default=False,
        ),
    ]
