# Generated by Django 2.0.3 on 2022-08-16 13:03

from django.db import migrations, models
from django.core.validators import FileExtensionValidator
import datetime
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_product_type_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(upload_to='product/video',null=True,
    validators=[FileExtensionValidator(allowed_extensions=['MOV','avi','mp4','webm','mkv'])])
        ),

        migrations.AlterField(
            model_name='product',
            name='product_type',
            field= models.CharField(choices=[('performance_costumes','Performance costumes'), ('ladies', 'Ladies'), ('mens', 'Mens'), ('accessories', 'Accessories'), ('dance_shoes', 'Dance shoes')], max_length=30, verbose_name='Product type')
        ),
]
