# Generated by Django 2.0.3 on 2025-04-29 20:40
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='HomeCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')],
                        default='active',
                        max_length=10,
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                (
                    'image',
                    models.ImageField(
                        blank=True, null=True, upload_to='categories/'
                    ),
                ),
                ('link', models.URLField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Home Category',
                'verbose_name_plural': 'Home Categories',
            },
        ),
    ]