# Generated by Django 2.0.3 on 2021-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=30, verbose_name='Name page')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('text', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('published', 'Published'), ('unpublished', 'Unpublished'), ('moderated', 'Moderated')], default='published', max_length=30, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
